### ISSUE TITLE
ERROR: Game crashed - Exit Code: 0 - NOT RELATED, PLEASE DELETE

### ISSUE THREAD

**Issue by Bushcrafts** [yungnickyoung/YUNGs-Better-Mineshafts#71]
After installing YungsApi-1.16.4-Forge-12.jar I get a minecraft exit code: 0 crash. 

When I remove YungsApi-1.16.4-Forge-12.jar I get the following crash report.

I am using MC 1.16.5.

Let me know if there is anything else I can report. I'd like to use both of your mods :)

-- Head --
Thread: Render thread
Stacktrace:
	at net.minecraftforge.fml.CrashReportExtender.lambda$dumpModLoadingCrashReport$7(CrashReportExtender.java:88) ~[?:?] {re:classloading}
-- MOD bettercaves --
Details:
	Mod File: BetterCaves-Forge-1.16.4-1.1.2.jar
	Failure message: Mod bettercaves requires yungsapi 1.16.4-Forge-2 or above
		Currently, yungsapi is not installed
	Mod Version: 1.16.4-1.1.2
	Mod Issue URL: https://github.com/yungnickyoung/YUNGs-Better-Caves/issues
	Exception message: MISSING EXCEPTION MESSAGE
Stacktrace:
	at net.minecraftforge.fml.CrashReportExtender.lambda$dumpModLoadingCrashReport$7(CrashReportExtender.java:88) ~[?:?] {re:classloading}
	at net.minecraftforge.fml.CrashReportExtender$$Lambda$3690/38840646.accept(Unknown Source) ~[?:?] {}
	at java.util.ArrayList.forEach(ArrayList.java:1249) ~[?:1.8.0_51] {}
	at net.minecraftforge.fml.CrashReportExtender.dumpModLoadingCrashReport(CrashReportExtender.java:86) [?:?] {re:classloading}
	at net.minecraftforge.fml.client.ClientModLoader.completeModLoading(ClientModLoader.java:188) [?:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.lambda$null$1(Minecraft.java:508) [?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft$$Lambda$3674/1652280702.run(Unknown Source) [?:?] {}
	at net.minecraft.util.Util.func_215077_a(Util.java:430) [?:?] {re:classloading,xf:OptiFine:default}
	at net.minecraft.client.Minecraft.lambda$new$2(Minecraft.java:504) [?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft$$Lambda$3415/566710404.accept(Unknown Source) [?:?] {}
	at net.minecraft.client.gui.ResourceLoadProgressGui.func_230430_a_(ResourceLoadProgressGui.java:172) [?:?] {re:classloading,xf:OptiFine:default}
	at net.minecraft.client.renderer.GameRenderer.func_195458_a(GameRenderer.java:802) [?:?] {re:classloading,pl:accesstransformer:B,xf:OptiFine:default}
	at net.minecraft.client.Minecraft.func_195542_b(Minecraft.java:976) [?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:607) [?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:184) [?:?] {re:classloading,pl:runtimedistcleaner:A}
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_51] {}
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_51] {}
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_51] {}
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_51] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:51) [forge-1.16.5-36.2.8.jar:36.2] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider$$Lambda$437/2052452680.call(Unknown Source) [forge-1.16.5-36.2.8.jar:36.2] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-8.0.9.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-8.0.9.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-8.0.9.jar:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:82) [modlauncher-8.0.9.jar:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:66) [modlauncher-8.0.9.jar:?] {}

-- MOD bettermineshafts --
Details:
	Mod File: BetterMineshafts-Forge-1.16.4-2.0.4.jar
	Failure message: Mod bettermineshafts requires yungsapi 1.16.4-Forge-3 or above
		Currently, yungsapi is not installed
	Mod Version: 1.16.4-2.0.4
	Mod Issue URL: https://github.com/yungnickyoung/YUNGs-Better-Mineshafts/issues
	Exception message: MISSING EXCEPTION MESSAGE

**Comment by Bushcrafts** [comment]
Nevermind I suppose, I removed all my mods except your BeterCaves, BetterMineshafts and the YungsAPI and it works. It was an issue with Immersive Portals and my forge mod.
